CREATE TABLE IF NOT EXISTS traveler (
    id SERIAL PRIMARY KEY,
    email_address VARCHAR(100) UNIQUE NOT NULL,
    email_confirmed BOOLEAN DEFAULT FALSE,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings(
	traveler_id INT NOT NULL,
	CONSTRAINT fk_traveler FOREIGN KEY(traveler_id) REFERENCES traveler(id),
  is_dark BOOLEAN DEFAULT TRUE,
  font_family VARCHAR(50) DEFAULT 'default'
);

CREATE TABLE IF NOT EXISTS entry (
	id SERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(255),
	body TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	traveler_id INT NOT NULL,
	CONSTRAINT fk_traveler FOREIGN KEY(traveler_id) REFERENCES traveler(id)
);
